USE `summonernames`;

CREATE TABLE IF NOT EXISTS `history` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255),
	`ip` VARCHAR(255),
	`server` VARCHAR(255),
	`date_searched` TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `feedback` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`email` VARCHAR(255),
	`message` TEXT,
	`ip` VARCHAR(255)
);
